### ISSUE TITLE
Cleanup by key

### ISSUE THREAD

**Issue by niphlod** [chriso/gauged#4]
Hi,
    once the data is inserted, is there a way to delete all the data (or part of it) belonging to only one key ?
I'm looking for a function that clears the data older than x days, etc, for maintenance purposes, e.g., delete all 'requests' data older than 2014-01-01.
It seems that there's a clear_from() but it'll wipe from a timestamp "onwards", and for ALL keys ...

**Comment by niphlod** [comment]
ok. I guess better late than ever....... I got a working implementation of

    def clear(self, key, namespace=None, before_timestamp=None):

I still have to face the gauged_cache issue, but I'm facing a different one: how to update properly statistics... 
I can't see a smart way to recompute statistics once a key is, e.g., dropped.
@chriso : Any idea ?

**Comment by chriso** [comment]
@niphlod the statistics are per namespace rather than per key so it's not possible to patch the statistics after removing a single key.

**Comment by niphlod** [comment]
is that going to be a problem, aside from the fact that statistics wouldn't be up to date ?

**Comment by chriso** [comment]
I don't think it's a major issue, as long as it's documented.

**Comment by niphlod** [comment]
ok. can you take a look at this before I start iterating on other adapters ?

https://github.com/niphlod/gauged/tree/fix/4

if you're good with the new methods "api", and there's nothing wrong with the code, I'll add tests and docs too.

**Comment by chriso** [comment]
That's looking great, thanks!

**Comment by niphlod** [comment]
you're the one who had some really great ideas. I'm just trying to add small bits to make it more manageable/flexible.

BTW: the change in schema would probably clash with the current one: I'm aware of that and we'll discuss it further (I saw that the layout is there already, but needs additional care)

I'll post a PR soon.

**Comment by chriso** [comment]
Fixed by #5.
